# Changes here will be overwritten by Copier
#
# Updating `_src` could be helpful, see notes at:
# https://github.com/level12/coppy/wiki#creating-a-project
#
# Otherwise, NEVER EDIT MANUALLY
_commit: v1.20260828.1
_src_path: gh:level12/coppy
author_email: devteam@level12.io
author_name: Level 12
gh_org: level12
gh_repo: worek
project_name: Worek
py_module: worek
python_version: '3.13'
python_version_min: '3.11'
script_name: worek
use_circleci: false
use_codecov: true
use_gh_nox: true
use_js_cooldown: false
use_rumdl: true
