version: 2.1
commands:
  run_tests:
      steps:
          - checkout

          - run:
              name: folder listing for debugging
              command: ls -al

          - run:
              name: install tox and upgrade pip
              command: python3.5 -m pip install -U pip tox pipenv

          - run:
              name: version checks
              command: |
                  python --version
                  pip --version
                  virtualenv --version
                  tox --version

          - run:
              name: run tox
              command: tox

          - store_test_results:
              path: .ci/test-reports/

          - run:
              name: push code coverage
              command: bash <(curl -s https://codecov.io/bash) -X coveragepy -t 9e7f8728-d93b-4eb5-9a7f-04046a743329

jobs:
    pg96:
      environment:
          PGUSER: testuser
          PGPASSWORD: password

      docker:
          - image: level12/python-test-multi
          - image: postgres:9.6
            environment:
                POSTGRES_USER: testuser
                POSTGRES_PASSWORD: password
      steps:
        - run_tests

    pg10:
      environment:
          PGUSER: testuser
          PGPASSWORD: password

      docker:
          - image: level12/python-test-multi
          - image: postgres:10
            environment:
                POSTGRES_USER: testuser
                POSTGRES_PASSWORD: password
      steps:
        - run:
            name: install correct pg version
            command: apt-get update && apt-get install -y postgresql-client-10
        - run_tests

workflows:
  version: 2.1
  build:
    jobs:
      - pg96
      - pg10

